backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "/public" # Media files will be stored in the repo under images/uploads
public_folder: "/public" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - label: "FAQ's" # used in UI
    name: "faqs" # used in routes
    files:
      - label: "Class FAQ's"
        name: "class_faqs"
        file: "src/posts/faqs/class_faqs.json"
        fields:
          - label: Class FAQ List
            name: class_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
          - label: Upcoming Courses Question
            name: upcoming_courses_question
            widget: string
          - label:  Upcoming Courses Answer
            name: upcoming_courses_answer
            widget: markdown
      - label: "Volunteer FAQ's"
        name: "volunteer_faqs"
        file: "src/posts/faqs/volunteer_faqs.json"
        fields:
          - label: Teacher FAQ List
            name: teacher_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
          - label: Publicity FAQ List
            name: publicity_faq_list
            widget: list
            fields:
              - {label: Question, name: question, widget: string}
              - {label: Answer, name: answer, widget: string}
  - label: "Bylaws and Minutes" # used in UI
    name: "bylaws_minutes" # used in routes
    files:
      - label: "Corporation Bylaws"
        name: "corp_bylaws"
        file: "src/posts/downloads/corp_bylaws.json"
        fields:
          - label: "Corporation Bylaws"
            name: "corp_bylaws_list"
            widget: list
            fields:
              - {label: Date, name: date, widget: date, default: "", format: "MMMM Do, YYYY"}
              - {label: Item Name, name: item_name, widget: string}
              - label: file
                name: "file_path"
                widget: file
                media_folder: '/public/uploads/downloads/corpsbylaws'
      - label: "Meeting Minutes and Agendas"
        name: "meeting_records"
        file: "src/posts/downloads/meeting_records.json"
        fields:
          - label: "Meeting Minutes and Agendas"
            name: "meeting_records_list"
            widget: list
            fields:
              - {label: Date, name: date, widget: date, default: "", format: "MMMM Do, YYYY"}
              - {label: Item Name, name: item_name, widget: string}
              - label: Meeting Minute File
                name: "meeting_minute_file_path"
                widget: file
                media_folder: '/public/uploads/downloads/meetingrecords'
              - label: Agenda File
                name: "agenda_file_path"
                widget: file
                media_folder: '/public/uploads/downloads/meetingrecords'
  - label: "Newsletters" # used in UI
    name: "newsletters" # used in routes
    files:
      - label: "Newsletters"
        name: "newsletters"
        file: "src/posts/newsletters.json"
        fields:
          - label: "Newsletters"
            name: "newsletters_list"
            widget: list
            fields:
              - {label: Date of Newsletter (Add month and year of newsletter. Ignore date), name: date, widget: date, default: "", format: "MMMM YYYY"}
              - label: file
                name: "file_path"
                widget: file
                media_folder: '/public/uploads/newsletters'
  - label: "Courses" # used in UI
    name: "courses" # used in routes
    files:
      - label: "Courses"
        name: "curses"
        file: "src/posts/courses.json"
        fields:
          - label: "Courses"
            name: "courses_list"
            widget: list
            fields:
              - {label: Course Name, name: course_name, widget: string}
              - {label: Link to Class Description, name: class_description_link, widget: string}
              - label: Image
                name: "file_path"
                widget: image
                media_folder: '/public/uploads/coursesimg'
              - {label: Dropdown Course Description, name: dropdown_course_description, widget: markdown}
              - label: Image
                name: "dropdown_file_path"
                widget: image
                media_folder: '/public/uploads/coursesimg/dropdownImg'
  - label: "Syllabi" # used in UI
    name: "syllabi" # used in routes
    files:
      - label: "Syllabi"
        name: "syllabi"
        file: "src/posts/syllabi.json"
        fields:
          - label: "Syllabi"
            name: "syllabi_list"
            widget: list
            fields:
              - {label: Language (Add language in native tongue. Ex. If Chinese => 中文; If French => FRANÇAIS), name: language, widget: string}
              - {label: Link to Syllabi Document, name: link, widget: string}
              - label: Flag Image
                name: "file_path"
                widget: image
                media_folder: '/public/uploads/flagimg'
  - label: "Editable Texts" # used in UI
    name: "editable_texts" # used in routes
    files:
      - label: "Individual Learners and Schools"
        name: "ind_learners_and_schools"
        file: "src/posts/ind_learners_and_schools.json"
        fields:
          - {label: "Course Overview Bold Text", name: "indlearners_bold_text", widget: string}
          - {label: "Course Overview Body Text", name: "indlearners_body_text", widget: markdown}
  - label: "Google Forms" # used in UI
    name: "google_forms" # used in routes
    files:
      - label: "Google Form"
        name: "google_forms"
        file: "src/posts/google_form.json"
        fields:
          - label: "Register Google Form Embed Code"
            name: "register_form_code"
            widget: code
          - label: "Teacher Google Form Embed Code"
            name: "teacher_app_form_code"
            widget: code
          - label: "TA Google Form Embed Code"
            name: "ta_app_form_code"
            widget: code
          - label: "General Intern Google Form Embed Code"
            name: "general_intern_app_form_code"
            widget: code
          - label: "Publicity Intern Google Form Embed Code"
            name: "publicity_intern_app_form_code"
            widget: code
          - label: "Technical Intern Google Form Embed Code"
            name: "technical_intern_app_form_code"
            widget: code
  - label: "Enroll Links" # used in UI
    name: "enroll_links" # used in routes
    files:
      - label: "Enroll Links"
        name: "enroll_links"
        file: "src/posts/enroll_links.json"
        fields:
          - label: "Enroll Link for Ind Learners and Schools"
            name: "link"
            widget: string
  - label: "Teacher/TA/Intern Overviews" # used in UI
    name: "teacher_ta_intern_overviews" # used in routes
    files:
      - label: "Teacher Overview"
        name: "teacher_overview"
        file: "src/posts/teacher_overview.json"
        fields:
          - label: "Overview"
            name: "overview"
            widget: markdown
          - label: "Scheduling"
            name: "scheduling"
            widget: markdown
          - label: "Tasks (Add Bulleted List)"
            name: "tasks"
            widget: markdown
          - label: "Curriculum (Add Bulleted List)"
            name: "curriculum"
            widget: markdown
          - label: "Time Commitment (Add Bulleted List)"
            name: "time_commitment"
            widget: markdown
          - label: "Benefits (Add Bulleted List)"
            name: "benefits"
            widget: markdown
          - label: "Requirments (Add Bulleted List)"
            name: "requirments"
            widget: markdown
          - label: "Beneficial Qualifications (Add Bulleted List)"
            name: "beneficial_qualifications"
            widget: markdown
      - label: "TA Overview"
        name: "ta_overview"
        file: "src/posts/ta_overview.json"
        fields:
          - label: "Overview"
            name: "overview"
            widget: markdown
          - label: "Scheduling"
            name: "scheduling"
            widget: markdown
          - label: "Tasks (Add Bulleted List)"
            name: "tasks"
            widget: markdown
          - label: "Curriculum (Add Bulleted List)"
            name: "curriculum"
            widget: markdown
          - label: "Time Commitment (Add Bulleted List)"
            name: "time_commitment"
            widget: markdown
          - label: "Benefits (Add Bulleted List)"
            name: "benefits"
            widget: markdown
          - label: "Requirments (Add Bulleted List)"
            name: "requirments"
            widget: markdown
          - label: "Beneficial Qualifications (Add Bulleted List)"
            name: "beneficial_qualifications"
            widget: markdown
      - label: "Intern Overview"
        name: "intern_overview"
        file: "src/posts/intern_overview.json"
        fields:
          - label: "Overview"
            name: "overview"
            widget: markdown
          - label: "Intern Path"
            name: "internpath"
            widget: markdown
          - label: "Scheduling"
            name: "scheduling"
            widget: markdown
          - label: "Curriculum (Add Bulleted List)"
            name: "curriculum"
            widget: markdown
          - label: "Time Commitment (Add Bulleted List)"
            name: "time_commitment"
            widget: markdown
          - label: "Benefits (Add Bulleted List)"
            name: "benefits"
            widget: markdown
          - label: "Requirments (Add Bulleted List)"
            name: "requirments"
            widget: markdown
          - label: "Beneficial Qualifications (Add Bulleted List)"
            name: "beneficial_qualifications"
  - label: "Leadership Team Info" # used in UI
    name: "leadership_team_info" # used in routes
    files:
      - label: "Board Members"
        name: "board_members"
        file: "src/posts/board_members.json"
        fields:
          - label: "Board Members List"
            name: "board_members_list"
            widget: list
            fields:
              - label: "Name"
                name: "name"
                widget: string
              - label: "Title/Pronouns"
                name: "title_pronouns"
                widget: string
              - label: "Description"
                name: "description"
                widget: markdown  
              - label: "Image"
                name: "image"
                widget: image 
                media_folder: '/public/uploads/leadershipteamimg/boardmembers'
      - label: "Assistant Directors"
        name: "assistant_directors"
        file: "src/posts/assistant_directors.json"
        fields:
          - label: "Assistant Directors List"
            name: "assistant_directors_list"
            widget: list
            fields:
              - label: "Name"
                name: "name"
                widget: string
              - label: "Title/Pronouns"
                name: "title_pronouns"
                widget: string
              - label: "Description"
                name: "description"
                widget: markdown  
              - label: "Image"
                name: "image"
                widget: image 
                media_folder: '/public/uploads/leadershipteamimg/assistantdirectors'
      - label: "Curriculum Committee"
        name: "curriculum_committee"
        file: "src/posts/curriculum_committee.json"
        fields:
          - label: "Curriculum Committee List"
            name: "curriculum_committee_list"
            widget: list
            fields:
              - label: "Name"
                name: "name"
                widget: string
              - label: "Title/Pronouns"
                name: "title_pronouns"
                widget: string
              - label: "Description"
                name: "description"
                widget: markdown  
              - label: "Image"
                name: "image"
                widget: image
                media_folder: '/public/uploads/leadershipteamimg/curriculumcommittee'
      - label: "Publicity Committee"
        name: "pub_committee"
        file: "src/posts/pub_committee.json"
        fields:
          - label: "Publicity Committee List"
            name: "pub_committee"
            widget: list
            fields:
              - label: "Name"
                name: "name"
                widget: string
              - label: "Title/Pronouns"
                name: "title_pronouns"
                widget: string
              - label: "Description"
                name: "description"
                widget: markdown  
              - label: "Image"
                name: "image"
                widget: image
                media_folder: '/public/uploads/leadershipteamimg/pubcommittee'
